=== rhizodigital/Bowler-Scaffolding-Group/.astro/collections/authors.schema.json
{
  "$ref": "#/definitions/authors",
  "definitions": {
    "authors": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "bio": {
          "type": "string"
        },
        "role": {
          "type": "string"
        },
        "twitter": {
          "type": "string",
          "format": "uri"
        },
        "linkedin": {
          "type": "string",
          "format": "uri"
        },
        "instagram": {
          "type": "string",
          "format": "uri"
        },
        "image": {
          "type": "string"
        },
        "$schema": {
          "type": "string"
        }
      },
      "required": [
        "id",
        "name",
        "image"
      ],
      "additionalProperties": false
    }
  },
  "$schema": "http://json-schema.org/draft-07/schema#"
}

=== rhizodigital/Bowler-Scaffolding-Group/src/data/authors/authors.json
[
  {
    "id": "michael-sables",
    "name": "Michael Sables",
    "role": "Full Stack Developer",
    "bio": "Michael Sables is a software engineer and writer. He is passionate about technology and its impact on society. He enjoys sharing his knowledge with others and helping them learn new things.",
    "image": "./michael-sables.jpg"
  }
]
